[package]
name = "command-endpoint"
version = "0.1.0"
authors = ["Dejan Bosanac <dbosanac@redhat.com>"]
edition = "2018"
license = "Apache-2.0"

[dependencies]

anyhow = "1"
snafu = "0.6"

actix-rt = "1.1"
actix-service = "1"
actix-web = "3"
actix-web-httpauth = "0.5.0"

futures = "0.3"
futures-core = "0.3"
futures-util = "0.3"

envconfig = "0.9"

reqwest = "0.10"

serde = { version = "1", features = ["derive"] }
serde_json = "1"

uuid = { version = "0.8", features = ["v4"] }

env_logger = "0.7"
log = "0.4"

cloudevents-sdk = "0.3"
cloudevents-sdk-actix-web = "0.3"
cloudevents-sdk-reqwest = "0.3"

drogue-cloud-endpoint-common = { path = "../endpoint-common" }

dotenv = "0.15.0"
jsonwebtokens = "1.0.0-alpha.13"

awc = "2.0.0"